php-mqtt/client

src/MQTTClient.php
Creating an instance of `MQTTClient` without specifying the `clientId` argument was throwing a TypeError in `generateRandomClientId()` as `mt_rand()` returns an `int` but `uniqid()` expects `string`.
=> Fix: TypeError thrown from generateRandomClientId()

src/MQTTClient.php
If the MQTT daemon closes the connection before `MQTTClient` sends a keepalive ping the socket ends up broken and PHP issues a notice. Some frameworks halts the execution on all errors which makes it impossible to catch the `DataTransferException`  and reconnect.
This commit makes all `fread` and `fwrite` completely silent and hands over to the already built in error handling in `MQTTClient`.
=> Make reads and writes to sockets silent with the @-operator

src/MQTTClient.php
When using a username and password to connect to a broker, the message size has been manipulated using string concatenation instead of mathematical addition. This caused an issue with `chr()` expecting an integer and not a string. It also would have lead to wrong information being sent.
=> Fix: use addition to increase message size

.github/dependabot.yml
Since we purposefully use lower versions of dependencies, it makes sense to suggest only development updates.
=> dependabot: only suggest updates of dev packages

README.md, src/Concerns/OffersHooks.php, src/Contracts/MqttClient.php, src/Exceptions/ConnectingToBrokerFailedException.php, src/Exceptions/DataTransferException.php, src/Exceptions/MqttClientException.php, src/Exceptions/PendingPublishConfirmationAlreadyExistsException.php, src/Exceptions/UnexpectedAcknowledgementException.php
Follow-up for 3308d217e08ee420ca8d7184e305bf8ceadc9333
=> Rename the remaining MQTTClient* to MqttClient*

src/MQTTClient.php
When multiplexing between different streams there is the need to use stream_select() on the raw sockets, and then run for a single time into the main loop of the library. These two changes allow to do so.
=> Added possibility to retrieve the raw socket and loop externally

src/Contracts/MQTTClient.php, src/MQTTClient.php
If the publisher set the retained flag the broker will honor it and send the published messages to the subscriber as soon as he subscribes, but the subscribe callback might need to know whether the message was delivered live or if it was retained, which could mean the message is stale.
=> Added 'retained' parameter to subscriptions callbacks for published messages

.github/workflows/tests.yml, phpunit.xml
This PR adds a new `tests.yml` which runs unit and feature tests with `phpunit` using a matrix strategy on the following operating systems and PHP versions:
- Operating systems: `ubuntu-latest`, `windows-latest` and `macos-latest`
- PHP versions: `7.2`, `7.3` and `7.4`
=> A a workflow to run unit and feature tests

README.md
Just adds some documentation and examples to the README. The existing examples of the documentation are improved by adding the FQCNs.
=> Improve README by adding some examples

src/MQTTClient.php
For some packets the remaining length was encoded using `chr()`, but if the packet exceeded 129 bytes (i.e. 127 remaining length) it would become incorrectly encoded. This changes fixes the problem by always using the proper encoder method `encodeMessageLength()`. Also drops the buffer length counter as it is faster to just check for `strlen()`.
=> Fix protocol implementation error when certain packets are bigger than 129 bytes

src/ConnectionSettings.php, src/Exceptions/ConnectingToBrokerFailedException.php, src/MQTTClient.php
This change addresses several issues with the handling of failed connections, distinguishing three different *tiers* depending on the type of issue, which I try to outline below.
All errors are represented by the `ConnectingToBrokerFailedException`
For tier-specific error information, you can get message and code using the two additional methods in the exception. The user that is interesting in understanding more about the error can map and inspect these codes using external means.
* Represented by the `EXCEPTION_CONNECTION_SOCKET_ERROR` error code.
* Error message contains the raw sockets error message, code contains the POSIX socket error number (see  for a full list).
* Some examples are:
* Network is unreachable (ENETUNREACH - 101)
* Connection refused (ECONNREFUSED - 110)
* No route …
=> Improved connection error handling and TLS options

src/Contracts/Repository.php, src/MqttClient.php, src/Repositories/BaseRepository.php
The methods `addNewTopicSubscription()`, `addNewPendingPublishedMessage()`, and `addNewPendingPublishConfirmation()` are invoked only once in the MqttClient class and can be inlined to reduce the Repository interface.
=> Inline 'addNew[...]' methods to MqttClient to reduce Repository interface

.phpcs.xml, src/MQTTClient.php
Currently, the QoS 2 message flow is broken when the MQTT client is used to subscribe to topics with QoS 2 where messages are received with QoS 2. No `PUBREL` message is sent in response to a received `PUBREC` message.
=> Fix: Send PUBREL in response to PUBREC

README.md, src/ConnectionSettings.php, src/MQTTClient.php
Hello there,
I am creating this pull request after reading the following comment from Namoshek from https://github.com/php-mqtt/client/issues/34#issuecomment-675290524:
_'I would also be open for a pull request to add client certificate support to the 0.2 branch though!'_
I tried to use this library to connect to an MQTT Server from Amazon Web Services IoT, and finally managed to connect after adding some lines which set the 'local_cert' and 'local_key' properties on the SSL context. I'm not sure if the way I am passing the file paths to the MQTTClient class fits this libary's API design, so maybe someone familiar with this library could check if these changes could be merged into the project. Maybe it would be better to allow the caller to pass an array which will be merged into …
=> Add support for client certificates

.github/workflows/tests.yml, phpunit.xml
This PR changes the test workflow in a way which will run the tests using different MQTT brokers (Mosquitto, HiveMQ 4 and EMQ X). Doing so can help reduce issues with individual brokers.
=> Run test workflow using different MQTT brokers

README.md, src/Contracts/MqttClient.php, src/MqttClient.php
Since there is a `connect()` method, there should also be a `disconnect()` method. Until now, the `disconnect()` method was internal and used by `close()`. This PR renames `close()` to `disconnect()` and the internal `disconnect()` to `sendDisconnect()`.
=> Rename close() to disconnect()

README.md, composer.json, src/Concerns/OffersHooks.php, src/Contracts/MqttClient.php, src/Contracts/Repository.php, src/MqttClient.php, src/Repositories/MemoryRepository.php, src/Subscription.php, tests/Feature/MessageReceivedEventHandlerTest.php, tests/Unit/MessageProcessors/Mqtt31MessageProcessorTest.php
Serializing callbacks will not work with resources and similar types of code. The subscription id is currently not required and useable (MQTT 5 feature). When a clean session is used, the repository is cleared. Adds event handlers for received messages (can be used in combination with subscriptions without callback for example, or for logging). Other changes affect the overall code quality.
=> Do not serialize subscription callbacks, remove subscription id and quality changes

CHANGELOG.md, LICENSE.md, README.md, composer.json, src/ConnectionSettings.php, src/Logger.php
This PR prepares a release candiate for `v1.0.0` by adding a thorough changelog. The readme is updated as well, with slight changes only though. Before this gets merged, more examples are to be added in the [`php-mqtt/client-examples` repository](https://github.com/php-mqtt/client-examples).
TODO:
=> Update README and add CHANGELOG

.ci/tls/.gitignore, .github/workflows/tests.yml, README.md, create-certificates.sh, src/MqttClient.php, tests/Feature/ConnectWithTlsSettingsTest.php, tests/Feature/MessageReceivedEventHandlerTest.php
This PR adds a few more tests, especially for the following things:
- Remaining TLS options and a negative TLS test (when an exception is thrown)
- Unregistering a single _message received event handler_
Minor changes have been made to:
- `README`: the _test pipeline status_ badge was replaced with a _code coverage_ badge
- `MqttClient`:
- The log level used when a socket could not be closed was raised from `debug` to `notice`
- The `$exitWhenQueuesEmpty` condition in the `loop()` method was simplified (logic hasn't changed)
=> Add more tests

src/Subscription.php, tests/Feature/PublishSubscribeTest.php
With MQTT 5, support for _shared subscriptions_ has been added to the MQTT protocol. Since this is pretty much a server-side feature only, where the server has to distribute messages across clients within a group, the only thing a client needs to consider is the `$share/<group>` part of used topic filters. This allows us back-porting this feature to MQTT 3 on the client side.
This PR therefore adds support for such topic filters by stripping the `$share/<group>` part for the comparison during regexification of the topic filter in the repository. While shared subscriptions are not an MQTT 3 feature, [usage of topic names beginning with `$` is discouraged](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718108). We can therefore assume that our users are not using …
=> Add support for shared subscription topic names

.github/workflows/tests.yml, composer.json
This PR adds support for `^2.0` of [`psr/log`](https://github.com/php-fig/log).
Support for v2 is fully backwards compatible and does not require any code changes, while support for v3 would require us to add return types to the [`Logger`](https://github.com/php-mqtt/client/blob/ddff90f65e73c872e43d1629aeb8028f7d2b3201/src/Logger.php) which is a breaking change and requires a major version bump.
=> Add support for ^2.0 of psr/log

.github/workflows/tests.yml
This PR simply enables PHP 8.1 builds for pull requests and moves the SonarQube analysis to the PHP 8.1 build against Mosquitto as MQTT broker.
=> Run build pipeline also for PHP 8.1

src/MessageProcessors/Mqtt311MessageProcessor.php, src/MessageProcessors/Mqtt31MessageProcessor.php, src/MqttClient.php, tests/Feature/ConnectWithCustomConnectionSettingsTest.php, tests/Feature/SupportedProtocolsTest.php, tests/Unit/MessageProcessors/Mqtt311MessageProcessorTest.php
This PR adds a second message processor which makes the client compatible with MQTT 3.1.1. The default implementation is still MQTT 3.1, which makes this addition fully backwards compatible. The relevant changes between MQTT 3.1 and MQTT 3.1.1 can be found [here](https://github.com/mqtt/mqtt.org/wiki/Differences-between-3.1.0-and-3.1.1).
Reviews are welcome. @thg2k @nicoworq
=> Add support for MQTT 3.1.1

.github/release.yml
GitHub supports auto-generating changelogs from pull requests based on labels (see [here](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes)). This PR enables this feature.
=> Add .github/release.yml for auto-changelog

README.md, src/Concerns/ValidatesConfiguration.php, src/ConnectionSettings.php, src/MqttClient.php
As per the discussion in #104, this PR attempts to implement automatic reconnects. The implementation has this feature disabeld by default for backwards compatibility.
To simplify the code and avoid code duplication, `writeToSocket()` and `readFromSocket()` have been wrapped with the `writeToSocketWithAutoReconnect()` and `readFromSocketWithAutoReconnect()` counterparts. We also do not use auto-reconnect logic during connection handshakes to prevent recursion issues.
As of now, the PR lacks tests because it is quite difficult to have the broker disconnect the client on command. If anyone has an idea what logic could be used to force a disconnect server-side, I'd greatly appreciate it!
=> Support for automatic reconnects

.ci/mosquitto.conf, .github/workflows/tests.yml
Until now, the tests are only run against Mosquitto 1.6. In the mean time, Mosquitto 2.0 has been released (with quite a few patch versions already). Therefore, we also run the tests against Mosquitto 2.0 now.
=> Run CI tests against Mosquitto 2.0

.ci/mosquitto.conf, .ci/mosquitto.passwd, .github/workflows/tests.yml, phpunit.xml, tests/Feature/ConnectWithCustomConnectionSettingsTest.php, tests/TestCase.php
As there have been multiple reports in #105 about failing logins to Mosquitto after upgrading to Mosquitto 2, this PR adds integration tests to the build pipeline which ensure authentication works as expected with Mosquitto.
To achieve this, Mosquitto listenes on an additional port `1884` with enabled authentication whitelist (and disabled anonymous authentication). The pipeline uses a static hashed passwd file for the `ci-test-user`.
=> Run some integration tests with authentication

.github/workflows/tests.yml, README.md, phpunit.xml
This PR changes the port for MQTT with authentication used in `phpunit.xml`. It also updates the example command to run a local dev Mosquitto in the `README.md`.
Also does this PR change the version of HiveMQ we test in our CI build against to `v4.8.5` because the Java Key Store (JKS) we create in `create-certificates.sh` is being built with a never Java version and therefore the JKS cannot be read by HiveMQ `v4.4.4`.
=> Fix: Local test setup uses port 1884 for MQTT with authentication

README.md, src/Contracts/MqttClient.php, src/MqttClient.php, src/Repositories/MemoryRepository.php, src/Subscription.php, tests/Feature/PublishSubscribeTest.php
This PR introduces a new feature for subscriptions made on a wildcard topic. All matched wildcard parts of the topic are now extracted and passed to the subscription callback. This is best explained with an example:
```
Subscription made on topic pattern 'foo/bar/+'
Message received for topic 'foo/bar/baz'
The matched wildcard topic levels are passed to the subscription callback: ['baz']
Subscription made on topic pattern 'foo/+/bar/#'
Message received for topic 'foo/baz/bar/hello/world'
The matched wildcard topic levels are passed to the subscription callback: ['baz', 'hello/world']
```
The matched wildcards are passed as fourth parameter to the subscription callback:
```php
$mqtt->subscribe('foo/+/bar/#', function ($topic, $message, $retained, $matchedWildcards) {
echo sprintf("Received …
```
=> Pass matched topic wildcards to subscription callback

src/MqttClient.php
This PR fixes an issue where the MQTT client did not auto-reconnect during reads even if it was configured to do so. This issue has been raised in #129.
=> Fix: Auto-reconnect on read if configured

README.md, src/Concerns/ValidatesConfiguration.php, src/ConnectionSettings.php, src/MqttClient.php
As discussed in #129, the auto-reconnect feature only offers basic functionality as of right now. This PR therefore adds an additional connection setting for the delay between reconnect attempts `setDelayBetweenReconnectAttempts($delay)` which can be used in combination with `setReconnectAutomatically(true)` and `setMaxReconnectAttempts($attempts)`:
```php
$connectionSettings = (new \PhpMqtt\Client\ConnectionSettings)
->setReconnectAutomatically(true)
->setMaxReconnectAttempts(3)
->setDelayBetweenReconnectAttempts(0);
```
---
✔️ For backwards compatibility, the default delay between reconnect attempts is zero.
✔️ Integration tests for the auto-reconnect feature do not exist and are almost impossible to write, therefore this PR does not contain any tests. Manual tests have been performed. …
=> Add new connection setting for delay between reconnect attempts

README.md, src/ConnectionSettings.php, src/MqttClient.php, tests/Feature/PublishSubscribeTest.php
In #133 has been shown that sending large messages (e.g. binaries with a few hundred or thousand kilo bytes) does not work reliably and sometimes only the partial message is sent, leaving the receiver with a broken message. The source of the issue has been found in the `stream_set_blocking($socket, false)` call in the `MqttClient` class.
This PR therefore adds a connection setting for the blocking mode of the socket. It is recommended to leave this setting with the default, but in some rare scenarios it may be useful to not use a non-blocking but a blocking socket. The primary use case is when publishing large messages without using the `MqttClient::loop()` method.
=> Add connection setting for blocking mode of socket

.github/workflows/tests.yml
Other than the pull_request trigger, the pull_request_target runs against the workflow version of the target branch and grants the workflow access to secrets, which we need in our test runs.
=> Use pull_request_target trigger in test pipeline

README.md, src/ConnectionSettings.php, src/MqttClient.php
This PR replaces #139 and fixes the implementation of #135.
**Issue:**
Currently, the connection setting added in #135 has no effect due to a typo in the assignment.
**Background:**
Due to the nature of MQTT and how network communication works, non-blocking mode for sockets is quite essential when reading data received from the MQTT broker. If such reads are performed in blocking mode and no data is received from the broker over a long period of time, the connection may timeout.
**Solution:**
This PR fixes the typo in the connection settings. Because this fix introduces an issue when blocking mode is used for the socket, the meaning of the setting has been changed slightly. It now only affects the publishing of messages and is not used for reads on the socket.
=> Fix: Use blocking socket only during publishing if configured

src/ConnectionSettings.php
Added comments to help readers of the ConnectionSettings understand the reason for it's immutable behaviour. This will help with in-editor dynamically generated documentation (VSCode, intellisense, etc...).
=> ConnectionSettings class: Immutability documentation

src/Concerns/OffersHooks.php, src/ConnectionSettings.php, src/MqttClient.php, src/Repositories/MemoryRepository.php, tests/Feature/ConnectedEventHandlerTest.php, tests/Feature/PublishEventHandlerTest.php
This PR will add a new event handler list for an "connected"-event (ref #143).
I also had to add an duplicate check for the subscriptions, to prevent duplicated execution of the subscriptions callbacks.
I'm not sure if this should be the goal, maybe it could make more sense to add option for it or maybe clear the subscriptions if the connection is lost.
@Namoshek Do you have an idea for the duplicated subscription issue ?
=> Add connected event (handler)

src/MessageProcessors/Mqtt311MessageProcessor.php
In `src/MessageProcessors/Mqtt311MessageProcessor.php`
`parseAndValidateMessage` can return null values however `isPublishMessageWithNullCharacter` expects type to be `Message`.
This change aims to address `isPublishMessageWithNullCharacter` being able to also process null messages.
=> Fix: Allow isPublishMessageWithNullCharacter to receive messages as null

.github/workflows/tests.yml, src/Message.php, src/MessageProcessors/Mqtt31MessageProcessor.php, src/MqttClient.php, tests/Feature/PublishSubscribeTest.php
This PR adds the `retain` flag provided by MQTT brokers to delivered messages. For some reason, this was never implemented.
Details:
- The addition requires breaking a few of the internal APIs, hence this PR forces a major version bump at release.
- Because the tests for the retained flag will leak the published messages to other tests, some randomization was added for the topics used by these test cases.
=> Implement delivery of retain flag

README.md, src/ConnectionSettings.php, src/MqttClient.php
Added support for TLS ALPN to connect via MQTT protocol to a TLS encrypted HTTP port 443
With
->setTlsAlpn('mqtt')
it is now possible to use MQTT protocol on a TLS encrypted hTTP port 443 (server side has to support this).
=> Added support for TLS ALPN to connect via MQTT protocol to a TLS encrypted HTTP port 443

.github/workflows/tests.yml
This PR adds PHP 8.4 to the test pipeline (and removes the EOL version 8.0 of PHP).
=> Test against PHP 8.4

src/Concerns/OffersHooks.php, src/Contracts/MqttClient.php, src/Contracts/Repository.php, src/Exceptions/MqttClientException.php, src/MessageProcessors/Mqtt31MessageProcessor.php, src/MqttClient.php, src/PendingMessage.php, src/Repositories/MemoryRepository.php
This PR fixes #191 to fix implicitly nullable parameter declarations in PHP 8.4.
=> Fix: PHP 8.4 - Implicitly nullable parameter declarations deprecated
